apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: feature-serving
  namespace: <NAMESPACE>
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  default:
    predictor:
      minReplicas: 1
      custom:
        container:
          name: kfserving-container
          image: gcr.io/<PROJECT_ID>/mlops_world/kfservingcustom:latest
          env:
            - name: STORAGE_URI
              value: "gs://<BUCKET>/taxi/model"
          imagePullPolicy: Always
  
